---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk
  labels:
    app: sk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk
  template:
    metadata:
      labels:
        app: sk
    spec:
      containers:
      - name: sk
        image: robertbrem/sonnenkoenig:0.0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /sonnenkoenig/resources/ask
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: sk
spec:
  selector:
    app: sk
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31084
  type: NodePort
